# -*- coding: utf-8 -*-
"""assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjZACkGHtHBMI_gyxqn166CYVbeq4xd-

1. Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,between 2000 and 3200(both included).The numbers obtained should be printed in a comma-separated sequence on a single line.
"""

for i in range(2000,3200):
    if(i%7==0 and i%5!=0):
        print(i,end=",")

"""2. Write a Python program to accept the user's first and last name and then getting them printed in the reverse order with a space between first name and last name."""

first_name=input("Enter the first name")
last_name=input("Enter the last name")
print(first_name[::-1]+" "+last_name[::-1])

"""3. Write a Python program to find the volume of a sphere with diameter 12 cm."""

diameter=12
volume=4/3*3.14*((diameter//2)**3)
print("volume of sphere",volume)